### ISSUE TITLE
Think about graphs (and other visualizations) we want to do

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#124]
We need to think about what visualizations we actually want to do.

Proposal:

- Make one API request per visualization (since this means we build the frontend in a 'one visualization == one component' kind of way).

- This will mean that the current `/api/dashboards` and `/api/dashboards/id` calls will become simpler (The detail request now sends all aggregate info; that will become less; instead having different requests per graph).

Also nice is that we can then easily add parameters to the time-ranges we want to query etc.

**Comment by Qqwy** [comment]
Oh, and also re-look at the stuff Patrick wrote in his original document

**Comment by Qqwy** [comment]
The findings can be added to the Requirements Doc :-)

**Comment by ArjanTilstra** [comment]
Don't we need to do all the visualisations present in the original Flask Monitoring Dashboard?

**Comment by dunnkers** [comment]
> Don't we need to do all the visualisations present in the original Flask Monitoring Dashboard?

Agree. However, not all graphs in the original dashboard make that much sense with the current data set: the heatmap was fed with too little data to actually show something relevant. We'll try to at least visualize as much data as was shown in Patrick's dashboard, and then, probably, some more 🙂.

**Comment by InputUsername** [comment]
Yep, all visualisations of the Flask Monitoring Dashboard will need to be supported.

This issue is mostly about the way we want to structure the backend API to allow for flexibility for visualisations. For example an `/api/dashboards/<id>/visitors_per_day` endpoint etc. instead of including everything in the `/api/dashboards` and `/api/dashboards/<id>` calls. This way the frontend can support self-contained components for each visualisation.

**Comment by Qqwy** [comment]
Superseeded by #105.
