### ISSUE TITLE
Uptime Checking

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#309]
Ping every five minutes if the dashboard is up or not.

**Comment by InputUsername** [comment]
The branch `backend/uptime_checking` contains the functionality to frequently ping all dashboards (currently every 5 minutes) and record uptime data such as intervals of downtime, downtime percentage and total downtime. Due to the ZEO conflict problems related to our periodic task scheduler these changes fail to be persisted. The functionality works as intended though.

**Comment by Qqwy** [comment]
@InputUsername Create a PR to merge those changes; we won't finish the front-end part for this before the deadline, but then the back-end part is at least in the final build.
