### ISSUE TITLE
Seeding problem

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#322]
The seeding currently is extremely slow, and we do not know why.

**Comment by InputUsername** [comment]
I think it's simply because the app has been running for a while and the first request is a while ago. Fetching happens in blocks of 1 hour at the moment, so it likely performs hundreds of HTTP requests per dashboard. Manually turning the block size up to 10 weeks makes fetching almost instant.

**Comment by TWEApol** [comment]
Since the current version of `development` has fetching set at blocks of 1 week, this issue is not hampering further development anymore.

As a side note: I think we should keep our periodic fetching at ~1 hour periods, while we _may_ want to up our historic fetching a bit, as it is a one-time only thing. The only question is: what is a reasonable block size for an already long-lived FMD, such that we do not request too much information per request? What would be the best block size for an averagely busy FMD?

In the distant future, when registering a dashboard, we might want to ask the user an approximation of their FMD's lifespan and average busyness (e.g. endpoint-calls/week), in order to dynamically set their historical and/or periodic fetching block size.
