### ISSUE TITLE
Make react page to link to when verifying a user.

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#358]
When verifying a new user, they are sent an email with a link to this page in order to verify their account.
The back-end endpoint for account verification is already finished and waiting to be merged in the #359 PR, namely `/api/user/verify` with the verification-code in the POST-data.
The url for this page can be something like `/verify_user/<verification-code>`, as then the verification code itself can be retrieved from the url.

Upon retrieving a 200 status code from the back-end response, the user should be redirected to the login page (preferably with an indication that the verification has succeeded).
Upon retrieving a 400 status code from the back-end response, the user should be redirected to the login page (preferably with an indication that the verification has failed and the cause of the failure).

Note that in order for the front-end to test this, the previous back-end endpoint using `/api/user/verify/<verification-code>` has been dismantled, so we currently cannot create new accounts.

**Comment by Qqwy** [comment]
For future reference: The dismantling of the existing path is the kind of stuff to keep separate from `development` (after all, the front-end person working on this can just use that branch) because it breaks the functionality for others to work on other issues related to user registration.

But it's too late now; just so you know for next time ;-)
