### ISSUE TITLE
Add content to endpoint-specific page

### ISSUE THREAD

**Issue by ArjanTilstra** [RUGSoftEng/2018-PyDash.io#401]
Seeing as this page is still completely empty, something needs to be added.

 - Visitor graph (heatmap?)
 - Execution times (table?)

**Comment by Qqwy** [comment]
We should attempt to re-use all graphs we have for the dashboard as a whole (except the 'per endpoint' graphs because those would only contain a single bar).

Easiest probably is to extract the stuff in the `statistics_page`to a different folder, and make them agnostic in if they require `/dashboard/:dashboard_id/some_graph` vs `/dashboard/:dashboard_id/endpoint/:endpoint_name/some_graph` to fetch their information.
